spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/api_spring
    username: api_spring
    password: api_spring

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true